### ISSUE TITLE
[LISTING REQUEST]

### ISSUE THREAD

**Issue by This-Is-Prince** [saumyakaran/dotappstore#4]
## Project Overview
**Project:** Townhall
**Tagline:** Townhall an off-chain governance and collaboration platform
**Website link:** https://townhallgov.com/
**Description:** Townhall is a decentralized voting system. It provides flexibility on how voting power is calculated for a vote. Tonwhall supports various voting types to cater to the needs of organizations. Creating proposals and voting on Townhall is user-friendly and does not cost gas as the process is performed off-chain.
**Logo:** https://i.postimg.cc/xj76KC67/Town-Hall-Icon-Original.png

## Screenshots
![Home](https://i.postimg.cc/8zWvqkB7/Screenshot-2023-07-19-at-6-27-03-AM.png)
![House](https://i.postimg.cc/d1TDT4HL/Screenshot-2023-07-19-at-6-27-42-AM.png)
![Proposal](https://i.postimg.cc/QtLhvsmd/Screenshot-2023-07-19-at-6-28-36-AM.png)

## Project status
- [ ] Live on Mainnet or Testnet
- [x] Currently building

## Socials

- **Twitter:** https://twitter.com/townhallgov

**Comment by saumyakaran** [comment]
Added: https://github.com/iammasterbrucewayne/dotappstore/commit/201a534f7b14156b6ab88afce39e324f5f9ead06
