### ISSUE TITLE
[LISTING REQUEST] polkatax.com

### ISSUE THREAD

**Issue by polkatax** [saumyakaran/dotappstore#5]
## Project Overview
**Project:** PolkaTax
**Tagline:** A staking rewards calculator for Polkadot and other substrate chains
**Website link:** https://polkatax.com
**Description:** Seamlessly track and export staking rewards across Polkadot and other substrate chains in both crypto and fiat currencies for effortless taxation and monitoring.
**Logo:** ![logo](https://i.imgur.com/DjNsb5u.png) 

## Screenshots (optional)
![Screenshot_1](https://i.imgur.com/obkibYO.png) 
![Screenshot_2](https://i.imgur.com/Ku4hv7C.png) 

## Project status
How far along is the project? (please select ONE)

- [x] Live on Mainnet or Testnet
- [ ] Currently building

## Socials

- **github:** https://github.com/loanMaster/polkatax

## Additional Information
This project received a tip from the [Polkadot treasury](https://polkadot.polkassembly.io/referenda/100)

**Comment by saumyakaran** [comment]
Added: https://github.com/iammasterbrucewayne/dotappstore/commit/201a534f7b14156b6ab88afce39e324f5f9ead06
